<!DOCTYPE html><html lang="zh-CN"><head><meta name="generator" content="Hexo 3.8.0"><meta charset="utf-8"><meta name="X-UA-Compatible" content="IE=edge"><meta name="author" content="hikerpig,hikerpigwinnie@gmail.com"><title>在 Typescript 中继承 Error 对象 · HP goes FE</title><meta name="description" content="通过 Typescript class 继承 Error 实现自定义错误类型时，遇到了一个坑。
class MyError extends Error &amp;#123;&amp;#125;
但是运行起来：
const err = new MyError()
err instanceof Error // tru"><meta name="keywords" content="Front-End,Programming,Hexo"><meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"><meta content="yes" name="apple-mobile-web-app-capable"><meta content="black" name="apple-mobile-web-app-status-bar-style"><meta content="telephone=no" name="format-detection"><meta name="renderer" content="webkit"><link rel="short icon" href="/images/favicon.png" type="image/x-icon"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/blog_basic.css"><link rel="stylesheet" href="/css/font-awesome.min.css"><link rel="alternate" type="application/atom+xml" title="ATOM 1.0" href="/atom.xml"></head><body><div class="sidebar animated fadeInDown"><div class="logo-title"><div class="title"><img src="/images/avatar.jpeg" class="sidebar__avatar"><h3 title=""><a href="/">HP goes FE</a></h3><div class="description"><p>Note for everything</p></div></div></div><ul class="social-links"><li><a href="http://github.com/https://github.com/hikerpig"><i class="fa fa-github"></i></a></li></ul><div class="sidebar-nav animated fadeInDown"><div class="nav"><li><a href="/">首页</a></li><li><a href="/archives">归档</a></li></div><div class="information"><div class="back_btn"><a onclick="window.history.go(-1)" class="fa fa-chevron-left"></a></div></div></div><div class="footer"><a target="_blank" href="/"><span>Theme by  </span></a><a href="https://github/hikerpig">Hikerpig </a><span>forked from </span><a href="https://github.com/Ben02/hexo-theme-Anatole">Anatole</a><div class="by_farbox"><a href="https://hexo.io/zh-cn/" target="_blank">Proudly published with Hexo</a></div></div></div><div class="main"><div class="autopagerize_page_element"><div class="content"><div class="post-page"><div class="post animated fadeInDown"><div class="post-title"><h1><a>在 Typescript 中继承 Error 对象</a></h1></div><div class="post-content"><p>通过 Typescript class 继承 Error 实现自定义错误类型时，遇到了一个坑。</p>
<pre><code class="hljs typescript"><span class="hljs-keyword">class</span> MyError <span class="hljs-keyword">extends</span> <span class="hljs-built_in">Error</span> &#123;&#125;</code></pre>
<p>但是运行起来：</p>
<pre><code class="hljs typescript"><span class="hljs-keyword">const</span> err = <span class="hljs-keyword">new</span> MyError()
err <span class="hljs-keyword">instanceof</span> <span class="hljs-built_in">Error</span> <span class="hljs-comment">// true</span>
err <span class="hljs-keyword">instanceof</span> MyError  <span class="hljs-comment">// 结果竟然是 false</span></code></pre>
<h2 id="原因">原因</h2>
<p>使用 Babel/Typescript 编译出的代码有类似的问题</p>
<p>Typescript 2.7.2 编译出的代码</p>
<pre><code class="hljs typescript"><span class="hljs-keyword">var</span> __extends = (<span class="hljs-keyword">this</span> &amp;&amp; <span class="hljs-keyword">this</span>.__extends) || (<span class="hljs-function"><span class="hljs-keyword">function</span> (<span class="hljs-params"></span>) </span>&#123;
    <span class="hljs-keyword">var</span> extendStatics = <span class="hljs-built_in">Object</span>.setPrototypeOf ||
        (&#123; __proto__: [] &#125; <span class="hljs-keyword">instanceof</span> <span class="hljs-built_in">Array</span> &amp;&amp; <span class="hljs-function"><span class="hljs-keyword">function</span> (<span class="hljs-params">d, b</span>) </span>&#123; d.__proto__ = b; &#125;) ||
        <span class="hljs-function"><span class="hljs-keyword">function</span> (<span class="hljs-params">d, b</span>) </span>&#123; <span class="hljs-keyword">for</span> (<span class="hljs-keyword">var</span> p <span class="hljs-keyword">in</span> b) <span class="hljs-keyword">if</span> (b.hasOwnProperty(p)) d[p] = b[p]; &#125;;
    <span class="hljs-keyword">return</span> <span class="hljs-function"><span class="hljs-keyword">function</span> (<span class="hljs-params">d, b</span>) </span>&#123;
        extendStatics(d, b);
        <span class="hljs-function"><span class="hljs-keyword">function</span> __(<span class="hljs-params"></span>) </span>&#123; <span class="hljs-keyword">this</span>.constructor = d; &#125;
        d.prototype = b === <span class="hljs-literal">null</span> ? <span class="hljs-built_in">Object</span>.create(b) : (__.prototype = b.prototype, <span class="hljs-keyword">new</span> __());
    &#125;;
&#125;)();
<span class="hljs-keyword">var</span> MyError = <span class="hljs-comment">/** @class */</span> (<span class="hljs-function"><span class="hljs-keyword">function</span> (<span class="hljs-params">_super</span>) </span>&#123;
    __extends(MyError, _super);
    <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">MyError</span>(<span class="hljs-params"></span>) </span>&#123;
        <span class="hljs-comment">// 问题关键在这里</span>
        <span class="hljs-keyword">return</span> _super !== <span class="hljs-literal">null</span> &amp;&amp; _super.apply(<span class="hljs-keyword">this</span>, <span class="hljs-built_in">arguments</span>) || <span class="hljs-keyword">this</span>;
    &#125;
    <span class="hljs-keyword">return</span> MyError;
&#125;(<span class="hljs-built_in">Error</span>));</code></pre>
<p>原因在于，Error 是一个特殊的存在，即是一个构造函数，也是一个普通函数。以下两种调用皆可返回 error object。</p>
<pre><code class="hljs js"><span class="hljs-built_in">Error</span>(<span class="hljs-string">'message'</span>)
<span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'message'</span>)</code></pre>
<p>那么在调用以下函数时，_super 为 Error，返回的即是 <code>Error(this, arguments)</code>，而不是 <code>this</code> 。</p>
<pre><code class="hljs typescript">_super !== <span class="hljs-literal">null</span> &amp;&amp; _super.apply(<span class="hljs-keyword">this</span>, <span class="hljs-built_in">arguments</span>) || <span class="hljs-keyword">this</span>;</code></pre>
<h2 id="在-typescript-中">在 Typescript 中</h2>
<p>翻了翻文档，Typescript 2.1 的一些 <a href="https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work" target="_blank" rel="noopener">breaking change</a> 导致对于一些原生对象(Error/Array/Map)的继承无法正常工作，应该就是由 generated code 的改变造成的。官方给出的一个建议是：</p>
<pre><code class="hljs typescript"><span class="hljs-keyword">class</span> FooError <span class="hljs-keyword">extends</span> <span class="hljs-built_in">Error</span> &#123;
  <span class="hljs-keyword">constructor</span>(<span class="hljs-params">m: <span class="hljs-built_in">string</span></span>) &#123;
    <span class="hljs-keyword">super</span>(m)
    <span class="hljs-comment">// 在 super 之后立刻调用，改变实例的 prototype.</span>
    <span class="hljs-built_in">Object</span>.setPrototypeOf(<span class="hljs-keyword">this</span>, FooError.prototype)
  &#125;
&#125;</code></pre>
<p>但是这个写法其实相当的傻，因为对于每一个子类的构建函数来说，在改变原型之前，是无法拿到正确的子类实例 ‘this.constructor’ 的，所以 <code>Object.setPrototypeOf</code> 需要出现在所有子类的构建函数中。</p>
<h2 id="解决方案">解决方案</h2>
<p>只好把原型继承拿回来了，最终解决方案：</p>
<pre><code class="hljs typescript"><span class="hljs-keyword">export</span> <span class="hljs-keyword">class</span> ExtensibleError <span class="hljs-keyword">implements</span> <span class="hljs-built_in">Error</span> &#123;
  message: <span class="hljs-built_in">string</span>
  name: <span class="hljs-built_in">string</span>

  <span class="hljs-keyword">constructor</span>(<span class="hljs-params">message?: <span class="hljs-built_in">string</span></span>) &#123;
    <span class="hljs-built_in">Error</span>.apply(<span class="hljs-keyword">this</span>, <span class="hljs-built_in">arguments</span>)

    <span class="hljs-keyword">this</span>.message = message || <span class="hljs-string">''</span>
    <span class="hljs-keyword">this</span>.name = <span class="hljs-keyword">this</span>.constructor.name

    <span class="hljs-keyword">if</span> (<span class="hljs-keyword">typeof</span> <span class="hljs-built_in">Error</span>.captureStackTrace === <span class="hljs-string">'function'</span>) &#123;
      <span class="hljs-built_in">Error</span>.captureStackTrace(<span class="hljs-keyword">this</span>, <span class="hljs-keyword">this</span>.constructor)
    &#125;
  &#125;
&#125;

ExtensibleError.prototype = <span class="hljs-built_in">Object</span>.create(<span class="hljs-built_in">Error</span>.prototype)</code></pre>
<p>构建一个中间的辅助类，并不直接采用 class 继承 Error，而只实现 Error 接口，采用原型继承，此类的示例可经过 <code>instanceOf</code> 的检验。通过 <code>Error.captureStackTrac</code> 在初始化此类实例时能够捕获调用栈。</p>
<pre><code class="hljs typescript"><span class="hljs-keyword">class</span> MyError <span class="hljs-keyword">extends</span> ExtensibleError &#123;
&#125;

<span class="hljs-keyword">const</span> err = <span class="hljs-keyword">new</span> MyError()
err <span class="hljs-keyword">instanceof</span> ExtensibleError  <span class="hljs-comment">// true</span>
err <span class="hljs-keyword">instanceof</span> MyError  <span class="hljs-comment">// true</span>
err <span class="hljs-keyword">instanceof</span> <span class="hljs-built_in">Error</span> <span class="hljs-comment">// true</span></code></pre>
<p>参考</p>
<ul>
<li><a href="https://github.com/thundernet8/Blog/issues/1" target="_blank" rel="noopener">Error继承踩坑记</a></li>
<li><a href="https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work" target="_blank" rel="noopener">breaking change</a></li>
<li><a href="https://stackoverflow.com/questions/12915412/how-do-i-extend-a-host-object-e-g-error-in-typescript" target="_blank" rel="noopener">so 上的一个答案</a></li>
</ul>
</div><div class="post-footer"><div class="meta"><div class="info"><i class="fa fa-sun-o"></i><span class="date">2018-04-02</span><i class="fa fa-tag"></i><a href="/categories/前端/" title="前端" class="tag">前端 </a><a href="/tags/Javascript/" title="Javascript" class="tag">Javascript </a><a href="/tags/Typescript/" title="Typescript" class="tag">Typescript </a></div></div></div></div><div class="share"><div class="evernote"><a href="javascript:(function(){EN_CLIP_HOST='http://www.evernote.com';try{var%20x=document.createElement('SCRIPT');x.type='text/javascript';x.src=EN_CLIP_HOST+'/public/bookmarkClipper.js?'+(new%20Date().getTime()/100000);document.getElementsByTagName('head')[0].appendChild(x);}catch(e){location.href=EN_CLIP_HOST+'/clip.action?url='+encodeURIComponent(location.href)+'&amp;title='+encodeURIComponent(document.title);}})();" ref="nofollow" target="_blank" class="fa fa-bookmark"></a></div><div class="weibo"><a href="javascript:void((function(s,d,e){try{}catch(e){}var f='http://service.weibo.com/share/share.php?',u=d.location.href,p=['url=',e(u),'&amp;title=',e(d.title),'&amp;appkey=2924220432'].join('');function a(){if(!window.open([f,p].join(''),'mb',['toolbar=0,status=0,resizable=1,width=620,height=450,left=',(s.width-620)/2,',top=',(s.height-450)/2].join('')))u.href=[f,p].join('');};if(/Firefox/.test(navigator.userAgent)){setTimeout(a,0)}else{a()}})(screen,document,encodeURIComponent));" class="fa fa-weibo"></a></div><div class="twitter"><a href="http://twitter.com/home?status=,http://hikerpig.github.io/2018/04/02/2018-04-02-Customize-Error-in-Typescript/,HP goes FE,在 Typescript 中继承 Error 对象,;" class="fa fa-twitter"></a></div></div><div class="pagination"><ul class="clearfix"><li class="pre pagbuttons"><a role="navigation" href="/2018/04/06/2018-04-06-Write-Vue-Tests-in-Jest/" title="用 Jest 单元测试基于 Vue 的项目" class="btn">上一篇</a></li><li class="next pagbuttons"><a role="navigation" href="/2018/01/21/2018-01-21-typed-vue-mixins/" title="在 Typescript 中使用可被复用的 Vue Mixin" class="btn">下一篇</a></li></ul></div><div id="comments"><div id="gitalk-container"></div></div><link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css"><script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script><script>var gitalk = new Gitalk({
  clientID: '0b21579fda2f1d2e73f4',
  clientSecret: 'abc0351a314cc46bb3d58b6dad62c670c2d1e8f9',
  repo: 'hikerpig.github.io',
  owner: 'hikerpig',
  admin: 'hikerpig',
  labels: ['Gitalk'],
  id: '2018/04/02/2018-04-02-Customize-Error-in-Typescript/',
  title: '在 Typescript 中继承 Error 对象',
  // facebook-like distraction free mode
  distractionFreeMode: false
})

gitalk.render('gitalk-container')
</script></div></div></div></div><script src="//cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script><script src="//cdn.jsdelivr.net/npm/jquery.appear"></script><!-- Global site tag (gtag.js) - Google Analytics--><script async src="https://www.googletagmanager.com/gtag/js?id=UA-49433257-1"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-49433257-1');
</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@9.13.1/styles/atom-one-dark.css"><script src="https://cdn.jsdelivr.net/npm/highlight.js@9.13.1/lib/highlight.js"></script><script>hljs.initHighlightingOnLoad();
</script></body></html>